apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineonlium
  labels:
    app: mineonlium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mineonlium
  template:
    metadata:
      labels:
        app: mineonlium
    spec:
      containers:
        - name: mineonlium
          image: tmjeff/mineonlium:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 60606

---

apiVersion: v1
kind: Service
metadata:
  name: mineonlium
spec:
  selector:
    app: mineonlium
  ports:
    - port: 8545
      protocol: TCP
      targetPort: 8545
      name: rpc
    - port: 60606
      protocol: TCP
      targetPort: 60606
      name: p2ptcp
    - port: 60606
      protocol: UDP
      targetPort: 60606
      name: p2pudp

---

apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "p2ptcp"
  namespace: "core"
spec:
  defaultBackend:
    service:
      name: "mineonlium"
      port:
        number: 60606
status:
  loadBalancer: {}
